# Generated by Django 5.1.4 on 2025-02-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_client_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
